const char *workerCols[] = {
	TABLECOL_AGENT, TABLECOL_AGENTVERSION, TABLECOL_AGENTBUSINESS,
	TABLECOL_NODE, TABLECOL_USER, TABLECOL_LOAD, TABLECOL_CPU, TABLECOL_MEM,
	TABLECOL_DISK, TABLECOL_NIC, TABLECOL_DEV,
	TABLECOL_RUN, TABLECOL_PROC, TABLECOL_DAEMON,
	TABLECOL_PORTS, TABLECOL_SOFTWARE, TABLECOL_SYSTEM
};

const char *workerKeys[] = {
	TABLEKEY_NODE, TABLEKEY_DOMAIN, TABLEKEY_SYSTEM
};

const char *workerTables[] = {
	TABLE_AGENTNAME, TABLE_AGENTVERSION, TABLE_AGENTBUSINESS,
	TABLE_NODEDATA, TABLE_USERDATA, TABLE_LOADDATA, TABLE_CPUDATA, TABLE_MEMORYDATA,
	TABLE_DISKDATA, TABLE_NICDATA, TABLE_DEVICEDATA,
	TABLE_RUNNING, TABLE_PROCESSES, TABLE_DAEMONS,
	TABLE_OPENPORTS,
	TABLE_SOFTWARE,
	TABLE_SYSTEM,
	NULL
};
