char **halDevices;

DBusConnection *dbusConnection;
DBusError dbusError;

LibHalContext *halContext;
LibHalPropertyType halPropertyType;
LibHalPropertySetIterator halIterator;

struct halPointer {
	char *name;
	int ptr;
};

struct halPointer halPointers[] = {
	{ "block.device", 0 },
	{ "block.is_volume", DATA_STRING_SIZE },
	{ "block.major", DATA_STRING_SIZE * 2 },
	{ "block.minor", DATA_STRING_SIZE * 3 },
	{ "block.storage_device", DATA_STRING_SIZE * 4 },
	{ "ide.channel", DATA_STRING_SIZE * 5 },
	{ "ide.host", DATA_STRING_SIZE * 6 },
	{ "info.addons", DATA_STRING_SIZE * 7 },
	{ "info.capabilities", DATA_STRING_SIZE * 8 },
	{ "info.category", DATA_STRING_SIZE * 9 },
	{ "info.interfaces", DATA_STRING_SIZE * 10 },
	{ "info.parent", DATA_STRING_SIZE * 11 },
	{ "info.product", DATA_STRING_SIZE * 12 },
	{ "info.subsystem", DATA_STRING_SIZE * 13 },
	{ "info.udi", DATA_STRING_SIZE * 14 },
	{ "info.vendor", DATA_STRING_SIZE * 15 },
	{ "info.addons.singleton", DATA_STRING_SIZE * 16 },
	{ "info.callouts.add", DATA_STRING_SIZE * 17 },
	{ "input.device", DATA_STRING_SIZE * 18 },
	{ "input.originating_device", DATA_STRING_SIZE * 19 },
	{ "input.product", DATA_STRING_SIZE * 20 },
	{ "net.address", DATA_STRING_SIZE * 21 },
	{ "net.arp_proto_hw_id", DATA_STRING_SIZE * 22 },
	{ "net.interface", DATA_STRING_SIZE * 23 },
	{ "net.originating_device", DATA_STRING_SIZE * 24 },
	{ "net.80203.mac_address", DATA_STRING_SIZE * 25 },
	{ "pci.device_class", DATA_STRING_SIZE * 26 },
	{ "pci.device_protocol", DATA_STRING_SIZE * 27 },
	{ "pci.device_subclass", DATA_STRING_SIZE * 28 },
	{ "pci.product_id", DATA_STRING_SIZE * 29 },
	{ "pci.subsys_product_id", DATA_STRING_SIZE * 30 },
	{ "pci.subsys_vendor_id", DATA_STRING_SIZE * 31 },
	{ "pci.vendor_id", DATA_STRING_SIZE * 32 },
	{ "platform.id", DATA_STRING_SIZE * 33 },
	{ "pnp.description", DATA_STRING_SIZE * 34 },
	{ "pnp.id", DATA_STRING_SIZE * 35 },
	{ "power_management.can_hibernate", DATA_STRING_SIZE * 36 },
	{ "power_management.can_suspend", DATA_STRING_SIZE * 37 },
	{ "power_management.can_suspend_hybrid", DATA_STRING_SIZE * 38 },
	{ "power_management.is_powersave_set", DATA_STRING_SIZE * 39 },
	{ "power_management.type", DATA_STRING_SIZE * 40 },
	{ "power_management.quirk.dpms_on", DATA_STRING_SIZE * 41 },
	{ "power_management.quirk.dpms_suspend", DATA_STRING_SIZE * 42 },
	{ "power_management.quirk.vbe_post", DATA_STRING_SIZE * 43 },
	{ "power_management.quirk.vbemode_restore", DATA_STRING_SIZE * 44 },
	{ "power_management.quirk.vbestate_restore", DATA_STRING_SIZE * 45 },
	{ "power_management.quirk.vga_mode_3", DATA_STRING_SIZE * 46 },
	{ "processor.can_throttle", DATA_STRING_SIZE * 47 },
	{ "processor.number", DATA_STRING_SIZE * 48 },
	{ "scsi_host.host", DATA_STRING_SIZE * 49 },
	{ "serio.description", DATA_STRING_SIZE * 50 },
	{ "serio.id", DATA_STRING_SIZE * 51 },
	{ "storage.automount_enabled_hint", DATA_STRING_SIZE * 52 },
	{ "storage.bus", DATA_STRING_SIZE * 53 },
	{ "storage.drive_type", DATA_STRING_SIZE * 54 },
	{ "storage.hotpluggable", DATA_STRING_SIZE * 55 },
	{ "storage.media_check_enabled", DATA_STRING_SIZE * 56 },
	{ "storage.model", DATA_STRING_SIZE * 57 },
	{ "storage.no_partitions_hint", DATA_STRING_SIZE * 58 },
	{ "storage.originating_device", DATA_STRING_SIZE * 59 },
	{ "storage.removable", DATA_STRING_SIZE * 60 },
	{ "storage.requires_eject", DATA_STRING_SIZE * 61 },
	{ "storage.size", DATA_STRING_SIZE * 62 },
	{ "storage.vendor", DATA_STRING_SIZE * 63 },
	{ "storage.removable.media_available", DATA_STRING_SIZE * 64 },
	{ "sound.card", DATA_STRING_SIZE * 65 },
	{ "sound.card_id", DATA_STRING_SIZE * 66 },
	{ "sound.originating_device", DATA_STRING_SIZE * 67 },
	{ "system.formfactor", DATA_STRING_SIZE * 68 },
	{ "system.board.product", DATA_STRING_SIZE * 69 },
	{ "system.board.serial", DATA_STRING_SIZE * 70 },
	{ "system.board.vendor", DATA_STRING_SIZE * 71 },
	{ "system.board.version", DATA_STRING_SIZE * 72 },
	{ "system.chassis.manufacturer", DATA_STRING_SIZE * 73 },
	{ "system.chassis.type", DATA_STRING_SIZE * 74 },
	{ "system.firmware.release_date", DATA_STRING_SIZE * 75 },
	{ "system.firmware.vendor", DATA_STRING_SIZE * 76 },
	{ "system.firmware.version", DATA_STRING_SIZE * 77 },
	{ "system.hardware.primary_video.product", DATA_STRING_SIZE * 78 },
	{ "system.hardware.primary_video.vendor", DATA_STRING_SIZE * 79 },
	{ "system.hardware.product", DATA_STRING_SIZE * 80 },
	{ "system.hardware.serial", DATA_STRING_SIZE * 81 },
	{ "system.hardware.uuid", DATA_STRING_SIZE * 82 },
	{ "system.hardware.vendor", DATA_STRING_SIZE * 83 },
	{ "system.hardware.version", DATA_STRING_SIZE * 84 },
	{ "system.kernel.machine", DATA_STRING_SIZE * 85 },
	{ "system.kernel.name", DATA_STRING_SIZE * 86 },
	{ "system.kernel.version", DATA_STRING_SIZE * 87 },
	{ "usb.bus_number", DATA_STRING_SIZE * 88 },
	{ "usb.can_wake_up", DATA_STRING_SIZE * 89 },
	{ "usb.configuration_value", DATA_STRING_SIZE * 90 },
	{ "usb_device_class", DATA_STRING_SIZE * 91 },
	{ "usb_device_protocol", DATA_STRING_SIZE * 92 },
	{ "usb_device_revision_bcd", DATA_STRING_SIZE * 93 },
	{ "usb_device_subclass", DATA_STRING_SIZE * 94 },
	{ "usb.is_self_powered", DATA_STRING_SIZE * 95 },
	{ "usb.max_power", DATA_STRING_SIZE * 96 },
	{ "usb.num_configurations", DATA_STRING_SIZE * 97 },
	{ "usb.num_interfaces", DATA_STRING_SIZE * 98 },
	{ "usb.num_ports", DATA_STRING_SIZE * 99 },
	{ "usb.product", DATA_STRING_SIZE * 100 },
	{ "usb.product_id", DATA_STRING_SIZE * 101 },
	{ "usb.serial", DATA_STRING_SIZE * 102 },
	{ "usb.speed", DATA_STRING_SIZE * 103 },
	{ "usb.vendor", DATA_STRING_SIZE * 104 },
	{ "usb.vendor_id", DATA_STRING_SIZE * 105 },
	{ "usb.version", DATA_STRING_SIZE * 106 },
	{ "usb.interface.class", DATA_STRING_SIZE * 107 },
	{ "usb.interface.number", DATA_STRING_SIZE * 108 },
	{ "usb.interface.protocol", DATA_STRING_SIZE * 109 },
	{ "usb.interface.subclass", DATA_STRING_SIZE * 110 },
	{ "usb_device.bus_number", DATA_STRING_SIZE * 111 },
	{ "usb_device.can_wake_up", DATA_STRING_SIZE * 112 },
	{ "usb_device.configuration_value", DATA_STRING_SIZE * 113 },
	{ "usb_device.device_class", DATA_STRING_SIZE * 114 },
	{ "usb_device.device_protocol", DATA_STRING_SIZE * 115 },
	{ "usb_device.device_revision_bcd", DATA_STRING_SIZE * 116 },
	{ "usb_device.device_subclass", DATA_STRING_SIZE * 117 },
	{ "usb_device.is_self_powered", DATA_STRING_SIZE * 118 },
	{ "usb_device.max_power", DATA_STRING_SIZE * 119 },
	{ "usb_device.num_configurations", DATA_STRING_SIZE * 120 },
	{ "usb_device.num_interfaces", DATA_STRING_SIZE * 121 },
	{ "usb_device.num_ports", DATA_STRING_SIZE * 122 },
	{ "usb_device.product", DATA_STRING_SIZE * 123 },
	{ "usb_device.product_id", DATA_STRING_SIZE * 124 },
	{ "usb_device.serial", DATA_STRING_SIZE * 125 },
	{ "usb_device.speed", DATA_STRING_SIZE * 126 },
	{ "usb_device.vendor", DATA_STRING_SIZE * 127 },
	{ "usb_device.vendor_id", DATA_STRING_SIZE * 128 },
	{ "usb_device.version", DATA_STRING_SIZE * 129 },
	{ NULL, 0 }
};
