#define CONFIG_LINEFEED 10
#define CONFIG_SPACE_SIZE 1024
#define CONFIG_STRING_SIZE 10240

#define CONFIG_DEFAULT_SHM "/var/run/tellud.shm"

#define CONFIG_OPTION_NOTREQUIRED 0
#define CONFIG_OPTION_REQUIRED 1

#define CONFIG_TYPE_BOOLEAN 1
#define CONFIG_TYPE_INTEGER 2
#define CONFIG_TYPE_STRING 3

#define CONFIG_TYPE_BOOLEAN_NO 0
#define CONFIG_TYPE_BOOLEAN_YES 1

#define DATA_BLOCK_SIZE 1024
#define DATA_COOKIE_SIZE 30
#define DATA_POINTER_SIZE 8

#define DATA_COMPRESS_NONE 0
#define DATA_COMPRESS_JIP 1

#define DAEMON_TELLUD 1
#define DAEMON_TELMOND 2
#define DAEMON_TELSKIND 3

#define ERROR_NOERROR 1
#define ERROR_SLIGHT 2
#define ERROR_FATAL 3

#define ITEM_DELIMITER 27
#define ITEM_SEPARATOR 26
#define ITEM_SPLITTER '|'

#define JIP_CCBITS 14
#define JIP_MAXVAL (1 << JIP_CCBITS) - 1
#define JIP_MAXCOD JIP_MAXVAL - 1

#if JIP_CCBITS == 14
	#define JIP_TBSIZE 18041
#endif
#if JIP_CCBITS == 13
	#define JIP_TBSIZE 9029
#endif
#if JIP_CCBITS <= 12
	#define JIP_TBSIZE 5021
#endif

#define MYSQL_HOSTNAME "localhost"
#define MYSQL_SOCKET "/var/run/mysqld/mysqld.sock"
#define MYSQL_PORT 3306
#define MYSQL_PORT_S "3306"
#define MYSQL_DATABASE "tellu3"
#define MYSQL_USERNAME "root"
#define MYSQL_PASSWORD ""

#define THREAD_AGAIN 1000000 / 1000
#define THREAD_TELLUD 50
#define THREAD_TELMOND 50
#define THREAD_TELSKIND 50

#define TIMEOUT_SOCKET 10

#define TIMER_RESOLUTION_STATUS 60 * 60
#define TIMER_RESOLUTION_STATUS_FLUSH "31536000"
#define TIMER_RESOLUTION_SESSION_FLUSH "14400"
#define TIMER_RESOLUTION_TEMP_FLUSH "14400"
#define TIMER_RESOLUTION_THREADSTOP 5

#define TIME_FORMAT "%a %d. %b %Y, %H:%M"
